app:
    resource: "@AppBundle/Controller/"
    type:     annotation

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation
auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController